import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/shared/Navbar";
import { cn } from "@/lib/utils";
import  { Toaster } from 'react-hot-toast';
import { Analytics } from '@vercel/analytics/react';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

    <html lang="en">

      <body className={cn(inter.className,"bg-slate-100")}>
        <Analytics/>
    <Toaster />
        <div>
          <Navbar/>
        </div>
        <main className="pt-16">
        {children}
        </main>
        </body>
    </html>
    </ClerkProvider>
  );
}
